name: foundee-max

services:
  bot:
    build: .
    container_name: foundee_max_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Роли пользователей и созданные вакансии сохраняются между перезапусками
      - .:/app #./app:/app
      - /app/node_modules # ./node_modules:/app/node_modules
      - ./certs:/app/certs
    environment:
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0 #отключение проверки TLS

